[exosphere]
debugmode=1
debugmode_user=0
disable_user_exception_handlers=0
enable_user_pmu_access=0
; 真实系统保留原始序列号，可正常联网使用正版游戏。
blank_prodinfo_sysmmc=0
; 虚拟系统屏蔽序列号，防止 CFW 环境暴露真机信息。
blank_prodinfo_emummc=1
allow_writing_to_cal_sysmmc=0
log_port=0
log_baud_rate=115200
log_inverted=0
